### ISSUE TITLE
AttributeError: 'MultirotorClient' object has no attribute 'getServerVersion'

### ISSUE THREAD

**Issue by Wingie** [microsoft/AirSim-NeurIPS2019-Drone-Racing#27]
Hi

this is my settings.json
```
{
  "SeeDocsAt": "https://github.com/Microsoft/AirSim/blob/master/docs/settings.md",
  "SettingsVersion": 1.2,
  "SimMode": "Multirotor"
}
```
and im getting this error when using the example code given
```
[(base) C:\Users\wings>python
Python 3.7.3 (default, Mar 27 2019, 17:13:21) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
KeyboardInterrupt
>>> import air
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'air'
>>> import airsimneurips as airsim
>>> client = airsim.MultirotorClient()
>>> client.confirmConnection()
Connected!
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\wings\Miniconda3\lib\site-packages\airsimneurips\client.py", line 128, in confirmConnection
    server_ver = self.getServerVersion()
AttributeError: 'MultirotorClient' object has no attribute 'getServerVersion'
>>> import airsim
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'airsim'
>>>
KeyboardInterrupt
>>>](url)
```

also to note that this works fine in another python env so its related to just the competition module
```
import airsim

# connect to the AirSim simulator 
client = airsim.MultirotorClient()
```

**Comment by madratman** [comment]
Just fixed this in airsimneurips v0.0.14
Can you please `pip2 / pip3 install airsimneurips --upgrade`

I removed `getServerVersion` for the neurips API to keep it lightweight in 0.0.13, but forgot to remove part of code elsewhere.
